### ISSUE TITLE
[flow] [Version 4] not working at all

### ISSUE THREAD

**Issue by jacargentina** [SublimeLinter/SublimeLinter#1041] opened 2018-03-02 10:59 UTC
I'm getting this on the SL console, after it auto-updated to v4

```
SublimeLinter: WARNING: eslint cannot locate 'eslint'  
SublimeLinter: WARNING: flow cannot locate 'flow'  
SublimeLinter: ERROR: Linter crashed. 
Traceback (most recent call last):   
File "lint.backend in /Users/javiercastro/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 97, in execute_lint_task   
File "lint.linter in /Users/javiercastro/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 794, in lint   
File "lint.linter in /Users/javiercastro/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 505, in get_cmd 
TypeError: 'NoneType' object is not iterable
```

Nothing else was changed (aslant is still there on the same path as before, etc)

**Comment by braver** [comment] 2018-03-02 11:12
I just published 4.0 of the eslint plugin, that should help. Also, restarting ST might be required.

**Comment by trych** [comment] 2018-03-02 13:04
Does not work at all for me, either.

Just freshly installed all `eslint`, `SublimeLinter` and `SublimeLinter-eslint`, created a `.eslintrc.js`. It just does not do anything at all, when I go `Lint this view`.

Any way I can retrieve some system stats to help out fix this?

**Comment by braver** [comment] 2018-03-02 13:09
There is a debug option in your settings. Enable it to get a bunch of useful output in the console.

**Comment by JeremyCraigMartinez** [comment] 2018-03-02 18:04
Getting this error too and this is all the output I get with debug set to true

**Comment by braver** [comment] 2018-03-02 18:59
@trych do you have the latest version of SublimeLinter-eslint now, and can you share the debug output?

@JeremyCraigMartinez or @jacargentina can you help me set up a test project for the flow linter?

**Comment by jacargentina** [comment] 2018-03-02 19:01
@braver it is working now in my case, I 've updated sublime linter-eslint to v4.0 as you pointed.

**Comment by braver** [comment] 2018-03-02 19:05
Ah, that's good at least. flow definitely seems broken though.

**Comment by JeremyCraigMartinez** [comment] 2018-03-02 19:10
I am already running SublimeLinter-eslint v4.0. I uninstalled and reinstalled it and it's still not taking. I don't know where I can find more debug output than what I've already shared in my last comment.

**Comment by jacargentina** [comment] 2018-03-02 19:13
I'm using flow too; I've discovered that babel-eslint 8.2.2 was not working, so downgrading to 8.2.1 it just works!

**Comment by kaste** [comment] 2018-03-02 19:42
flow should work okay unless you set flow-bin. Does anyone here uses that setting?

**Comment by braver** [comment] 2018-03-02 19:45
I just did a vanilla setup with no configuration at all and it failed for me with cmd being None.

**Comment by kaste** [comment] 2018-03-02 19:55
Yeah, I said 'okay'. When it doesn't find an executable it crashes. You know, I do code review. 😉

But if it finds an executable it should work okay. 🤗

**Comment by trych** [comment] 2018-03-02 20:02
Ok, not sure, if I am doing this right. I just install all the stuff and then run Lint this view and then I should see my errors marked in the gutter, right? (That's how it worked on my other machine when I used Sublime Linter a while ago).

When I run `Lint this view` nothing happens. 

When I turn on the debug mode, I get these messages in my console:

```
Unable to open /Users/trych/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/SublimeLinter.sublime-settings
reloading settings Packages/User/SublimeLinter.sublime-settings
SublimeLinter: SublimeLinter.sublime-package:71: Logging installed; log level INFO
```

As mentioned in another issue here, I also don't have any options to choose gutter style and a lot of other stuff that I used to have.

Also, on another issue there is mention of upgrading to `SublimeLinter-eslint 4.0.1`. But using my Package Control, it only shows me `SublimeLinter-eslint 4.0.0`. Is that correct?

**Comment by braver** [comment] 2018-03-02 20:07
eslint is at 4.0.0 so that's correct.

What is the debug output right after you run "lint this view"?

The commands to edit settings have been removed. Instead, you change settings by opening the settings and changing them, just like every other plugin. The default settings you'll see on the left will have lots of information about what's possible there. 

From the [update notification](https://github.com/SublimeLinter/SublimeLinter/blob/master/messages/4.0.0.txt):

> Commands to change settings or toggle linters have been removed.
> - Settings can be changed by modifying your user settings.
> - Linters may be disabled in the user settings,
>  or in your project configuration.

**Comment by trych** [comment] 2018-03-02 20:11
Sorry, please entirely ignore my issue for now, I suspect there is an issue with my eslint configuration.

**Comment by braver** [comment] 2018-03-02 20:16
@trych what usually happens for me with eslint is that it doesn't find the config file.

**Comment by kaste** [comment] 2018-03-02 20:20
Possible PR for flow is https://github.com/SublimeLinter/SublimeLinter-flow/pull/58

**Comment by braver** [comment] 2018-03-02 20:23
Oh, that's awesome. Flow users may want to check out and test that PR.

**Comment by trych** [comment] 2018-03-02 21:52
Ok, I'm back.

@braver You are right, it did not find `eslint-config-airbnb` in my case.

Now, after about 2 hours I managed to get eslint itself to run via the command line. Unfortunately, it still does not run at all in Sublime.

I still get this console output when I start up Sublime:

```
SublimeLinter: SublimeLinter.sublime-package:71: Logging installed; log level INFO
SublimeLinter: SublimeLinter.sublime-package:62: debug mode: on
SublimeLinter: SublimeLinter.sublime-package:63: version: 4.0.1
```

I get no output whatsoever when I run `Lint this view`. 😕 
Anything else I can try to help out?

**Comment by braver** [comment] 2018-03-02 21:58
If really nothing happens, the syntax may be incorrect, i.e. it may be a variant syntax that needs to be mapped. (We don’t have a lot of plugins that use the nex scope based solution for this). The settings have comments to help you figure out what the syntax is and how you should add it to the syntax_map setting.

**Comment by kaste** [comment] 2018-03-02 22:02
If it is that you could just set `'selector': 'source.js'` in the settings for eslint.

**Comment by kaste** [comment] 2018-03-02 22:04
Closing bc this was about flow initially which has a PR right now. But we're still subscribed.

**Closed by kaste** 2018-03-02 22:04 UTC
Labels: has PR, plugin?

**Comment by trych** [comment] 2018-03-02 22:11
> If really nothing happens, the syntax may be incorrect, i.e. it may be a variant syntax that needs to be mapped.

The syntax of what? My javascript file?
If I create a super simple javascript file to test, it does not work either. Now that the issue is closed, should I open a new one for my specific case? Or re-open this one?

**Comment by Jojo-Jojovich** [comment] 2018-03-02 22:21
I am having the same issue as @trych

**Comment by kaste** [comment] 2018-03-02 22:27
Please turn on 'background' mode in case the other modes are broken. Also did you try my `selector` suggestion? Otherwise, we still need the full output directly when starting Sublime with a js project open and js file directly getting active. 👍 

When we're closing we still are subscribed.

**Comment by Jojo-Jojovich** [comment] 2018-03-02 22:31
@kaste that fixed it for me, thank you!

**Comment by trych** [comment] 2018-03-02 22:37
Turned background mode back on, still does not work.

Here is the full console output after startup with a js file:

```
startup, version: 3157 osx x64 channel: dev
executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: /Users/trych/Library/Application Support/Sublime Text 3/Packages
state path: /Users/trych/Library/Application Support/Sublime Text 3/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/trych/Library/Application Support/Sublime Text 3/Installed Packages
ignored_packages: ["CSS", "Vintage"]
pre session restore time: 0.235354
startup time: 0.325604
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.colors
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin Default.ui
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin ShellScript.ShellScript
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.55-jsonschema
reloading plugin Browser Refresh.BrowserRefresh
reloading plugin Colorsublime.colorsublime-plugin
reloading plugin Compare Side-By-Side.sbs_compare
reloading plugin CSS3.css3_completions
reloading plugin CSS3.rgb_to_hex
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin SublimeLinter-eslint.linter
reloading plugin SublimeLinter.__init__
reloading plugin SublimeLinter.busy_indicator_view
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.goto_commands
reloading plugin SublimeLinter.highlight_view
reloading plugin SublimeLinter.log_handler
reloading plugin SublimeLinter.message_view
reloading plugin SublimeLinter.panel_view
reloading plugin SublimeLinter.status_bar_view
reloading plugin SublimeLinter.sublime_linter
reloading plugin SublimeLinter.tooltips_view
reloading plugin Run In InDesign.runInIndesign
plugins loaded
SublimeLinter: SublimeLinter.sublime-package:71: Logging installed; log level INFO
SublimeLinter: SublimeLinter.sublime-package:62: debug mode: on
SublimeLinter: SublimeLinter.sublime-package:63: version: 4.0.1
environment variables loaded using: /bin/bash -l
Package Control: Skipping automatic upgrade, last run at 2018-03-02 23:32:09, next run at 2018-03-03 00:32:09 or after
```

> Also did you try my selector suggestion?

> just set 'selector': 'source.js' in the settings for eslint

Sorry, where exactly do I need to set that?

**Comment by Jojo-Jojovich** [comment] 2018-03-02 22:41
@trych Edit your SublimeLinter package settings, and set that in the User settings.  This is what my settings look like, as an example:

```// SublimeLinter Settings - User
{
    "debug": false,
    "delay": 0.25,
    "gutter_theme": "Packages/SublimeLinter/gutter-themes/Default/Default.gutter-theme",
    "lint_mode": "background",
    "linters": {
        "eslint": {
            "@disable": false,
            "args": [],
            "excludes": [],
            "selector": "source.js"
        },
        "jshint": {
            "@disable": false,
            "args": [],
            "excludes": []
        },
        "jsxhint": {
            "@disable": false,
            "args": [],
            "excludes": []
        }
    }
}
```

**Comment by kaste** [comment] 2018-03-02 22:43
Cool. It seems SublimeLinter does not recognize the view/buffer as appropriate for eslint. 
Otherwise it would log `detected syntax: foo`

![image](https://user-images.githubusercontent.com/8558/36925454-4743f8b0-1e73-11e8-880b-2d424d2530f2.png)

You can take above settings if you have the eslint-plugin-html installed. 

@Jojo-Jojovich `@disabled` has become just `disabled` just in case.

**Comment by trych** [comment] 2018-03-02 22:50
Ok, sorry, that is definitively not how my User Settings looked. Transferring the settings that @Jojo-Jojovich just posted make SublimeLinter work now, however, now I get this error in the console, which I find strange as linting in the command line does work without any issues:

```
SublimeLinter: #1 eslint images.js ERROR:

 
Oops! Something went wrong! :(

ESLint: 4.18.2.
ESLint couldn't find the plugin "eslint-plugin-jsx-a11y". This can happen for a couple different reasons:

1. If ESLint is installed globally, then make sure eslint-plugin-jsx-a11y is also installed globally. A globally-installed ESLint cannot find a locally-installed plugin.

2. If ESLint is installed locally, then it's likely that the plugin isn't installed correctly. Try reinstalling by running the following:

    npm i eslint-plugin-jsx-a11y@latest --save-dev

If you still can't figure out the problem, please stop by https://gitter.im/eslint/eslint to chat with the team.
```

I had eslint and eslint-plugin-jsx-a11y installed globally (trying to run the eslint airbnb profile). Anybody knows what's wrong? 😞

**Comment by kaste** [comment] 2018-03-02 22:53
Usually NodeLinter finds and uses the locally installed eslint. So, all plugins must be locally as well.

**Comment by trych** [comment] 2018-03-02 23:08
Tried to install locally by using exactly the suggested command

```bash
npm i eslint-plugin-jsx-a11y@latest --save-dev
```

it still does not work. I wonder why it works on the command line but not via Sublime Linter, isn't that unusual?

**Comment by kaste** [comment] 2018-03-02 23:10
Yeah okay, but @trych you can still get more info when you open the console again. It should print the current working dir, the exact executable. I think it will print 'trying globally installed eslint' etc.

**Comment by kaste** [comment] 2018-03-02 23:14
You can force the executable by setting `'executable': 'full/path/to/eslint'`. You can force the working dir by setting `'working_dir'`. You could fake env settings  via `'env': {...}`

**Comment by trych** [comment] 2018-03-02 23:20
> You can force the executable by setting 'executable': 'full/path/to/eslint'

Thank you so much @kaste!
Setting it to `"executable": "/usr/local/bin/eslint"` made it immediately work. I wonder why I need to set this, though, when it seems to work without for everyone else? Do I have my system set up incorrectly?

Anyways, thanks a lot for your patience and for figuring this out for me!

**Comment by kaste** [comment] 2018-03-02 23:24
👍 😅
