### ISSUE TITLE
mark_style behaviour

### ISSUE THREAD

**Issue by orangecoloured** [SublimeLinter/SublimeLinter#1155] opened 2018-03-07 13:13 UTC
It would be nice to be able to control the `mark_style` that is used to highlight blocks of code.
As of now it works like this:
```
none => none,
fill => fill,
outline, solid_underline, squiggly_underline, stippled_underline => outline
```
And I'd like to use `underline` everywhere.

**Comment by FichteFoll** [comment] 2018-03-07 14:02
Duplicate of https://github.com/SublimeLinter/SublimeLinter/issues/1105.

**Closed** 2018-03-07 14:13 UTC
