### ISSUE TITLE
BrokenPipeError when linting (Windows 4k pipe limit)

### ISSUE THREAD

**Issue by limuyan** [SublimeLinter/SublimeLinter#347] opened 2015-10-14 08:31 UTC
```
SublimeLinter: chdir not set or invalid, using D:\work\YQTrackV5\(V5)YQTrack.Web\res\kit\js 
SublimeLinter: jshint: kit.js ['C:\\Users\\PPCC\\AppData\\Roaming\\npm\\jshint.cmd', '--verbose', '--filename', '@', '-'] 
Traceback (most recent call last):
  File "D:\Program Files\Sublime Text 3\sublime_plugin.py", line 256, in on_post_save
    callback.on_post_save(v)
  File "C:\Users\PPCC\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\sublimelinter.py", line 442, in on_post_save
    self.file_was_saved(view)
  File "C:\Users\PPCC\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\sublimelinter.py", line 464, in file_was_saved
    self.lint(vid)
  File "C:\Users\PPCC\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\sublimelinter.py", line 120, in lint
    Linter.lint_view(view, filename, code, hit_time, callback)
  File "C:\Users\PPCC\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\linter.py", line 919, in lint_view
    linter.lint(hit_time)
  File "C:\Users\PPCC\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\linter.py", line 1379, in lint
    output = self.run(cmd, self.code)
  File "C:\Users\PPCC\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\linter.py", line 1785, in run
    return self.communicate(cmd, code)
  File "C:\Users\PPCC\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\linter.py", line 1815, in communicate
    env=self.env)
  File "C:\Users\PPCC\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\util.py", line 1104, in communicate
    out = out.communicate(code)
  File "./subprocess.py", line 928, in communicate
  File "./subprocess.py", line 1206, in _communicate
BrokenPipeError: [Errno 32] Broken pipe
```

what happen?What should I do now?

**Comment by grotewold** [comment] 2015-10-16 00:20
This isn't a `chdir` error. I mean there IS a `chdir` message, but it's expected. It's actually the one below it. You are getting a `BrokenPipeError`, in Python this happens when a process stops before you can finish writing to it. Not sure what caused this. Does any other linter work for you? Can you link any file? Let me know so hopefully we can figure out the issue.

**Comment by BBB** [comment] 2015-10-19 13:31
@limuyan I had this same error. I fixed it by adding the `"chdir": "${project}"` key pair to each linter in my settings, as documented [here](https://github.com/SublimeLinter/SublimeLinter3/blob/5951b647e96370d36727eb6fcee6de5ae6b9a156/docs/linter_settings.rst) (It doesn't seem to have made it's way onto the readthedocs yet).

**Comment by erikku** [comment] 2016-02-21 23:56
I was trying to write a plugin today and ran into this same issue. I was working within Windows. After running the command manually and noticing that it did not crash or otherwise behave badly, I did some digging. I found that if the file being checked is over 4096 bytes, it starts dying in this way. That is the pipe buffer size.

If you look at the documentation for popen:
https://docs.python.org/3/library/subprocess.html#popen-objects

You will see this note for popen.communicate:
"The data read is buffered in memory, so do not use this method if the data size is large or unlimited."

On Windows, that buffer is 4K. This is why I'm getting the BrokenPipeError exception, not because of the linter crash. Long story short, I quickly hacked up the code in util.py to use files and not pipes and it works beautifully now.

Yes, this code needs work...

```python
def communicate(cmd, code=None, output_stream=STREAM_STDOUT, env=None):
    """
    Return the result of sending code via stdin to an executable.

    The result is a string which comes from stdout, stderr or the
    combining of the two, depending on the value of output_stream.
    If env is not None, it is merged with the result of create_environment.

    """

    # On Windows, using subprocess.PIPE with Popen() is broken when not
    # sending input through stdin. So we use temp files instead of a pipe.
    if os.name == 'nt':
        stdout = tempfile.TemporaryFile()
        stderr = tempfile.TemporaryFile()
        print(stdout.name)
        print(stderr.name)
    else:
        stdout = stderr = None

    if code is not None:
        code = code.encode('utf8')

    stdinFile = tempfile.TemporaryFile()
    stdinFile.write(code)

    cmd.append(stdinFile.name)

    out = popen(cmd, stdout=stdout, stderr=stderr, output_stream=output_stream, extra_env=env)

    if out is not None:
        out.wait()
        out = ['', '']

        if output_stream != STREAM_STDERR:
            stdout.seek(0)
            out[0] = stdout.read();
        if output_stream != STREAM_STDOUT:
            stderr.seek(0)
            out[1] = stderr.read();

        return combine_output(out)
    else:
        return ''
```

**Comment by kakysha** [comment] 2016-05-20 12:06
Getting the same error on Windows with my own Go linter. Error only happens on some .go files, others work great. Seems like the same 4k limit error with pipes.

My linter code:
```python
import os
from SublimeLinter.lint import Linter, util
class Gotype(Linter):
	"""Provides an interface to gotype."""

	syntax = ('go', 'gosublime-go')
	cmd = None
	executable = 'gotype'
	regex = r'^.+:(?P<line>\d+):(?P<col>\d+):\s+(?P<message>.+)'
	error_stream = util.STREAM_STDERR

	def cmd(self):
		project_folder = self.view.window().folders()[0]
		file_path = self.view.file_name()
		relative_file_path = file_path.split(project_folder)[1]
		gopath_file_path = os.environ['GOPATH'] + os.sep + 'src' + relative_file_path
		return (self.executable_path, '-e', '-a', gopath_file_path)

```

**Comment by kaste** [comment] 2018-01-17 11:30
@erikku Can't we just set `bufsize` to something more reasonable?

**Comment by FichteFoll** [comment] 2018-03-07 13:52
The default buffer size in my ST is 8k, btw. It might be lower on Windows.

```
>>> import io
>>> io.DEFAULT_BUFFER_SIZE
8192
```

The two possibilities are to either increase this or create files that are piped to manually. Since the former is considerably easier, I guess it's safe to just double or increase the bufsize by 50% to 8k/12k. The issue doesn't appear to be frequent.
If the latter is to be chosen, the files should be created in a `with` block.

**Comment by kaste** [comment] 2018-03-19 11:35
> Edit: Okay, I wasn't aware of how the current code looks like. It's a nightmare.

Haha, we inherited our mess.

FWIW

```
>>> io.DEFAULT_BUFFER_SIZE
8192
```

on Windows.

**Comment by kaste** [comment] 2018-03-19 11:40
Otherwise, `popen` constructor takes a `bufsize` arg.

**Comment by kaste** [comment] 2018-03-27 11:06
I'm closing this now as can't reproduce bc I can easily lint 'react.js' (uncompressed, dev version) which is > 600kB.

**Closed by kaste** 2018-03-27 11:06 UTC
Labels: can't replicate

**Comment by tssajo** [comment] 2018-04-11 11:14
@kaste please read my post at https://github.com/SublimeLinter/SublimeLinter/issues/1061
I can reproduce this bug 100% of the time on Windows 7 x64 when I am trying to lint a Go (aka. golang) file.

The error I receive is this:
```
SublimeLinter: #2 gotype b2-pdf.go ERROR:
=========================================

Linter crashed.

Traceback (most recent call last):
  File "lint.backend in C:\Users\User\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 100, in execute_lint_task
  File "lint.linter in C:\Users\User\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 761, in lint
  File "lint.linter in C:\Users\User\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 1005, in run
  File "lint.linter in C:\Users\User\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 1054, in communicate
  File "lint.util in C:\Users\User\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 226, in communicate
  File "./python3.3/subprocess.py", line 920, in communicate
  File "./python3.3/subprocess.py", line 1206, in _communicate
BrokenPipeError: [Errno 32] Broken pipe
```

Please consider re-opening this issue.

Thanks!

**Comment by kaste** [comment] 2018-04-11 11:54
This can easily be a problem with `gotype`. Currently, we send buffer content via stdin, although `gotype` does not expect or uses that (It is configured to lint the dir of the file afair.)

You should try `master` first. But since you can repro 100% and @kakysha above also used `gotype` 💩 maybe `gotype`plugin needs to be rewritten.

**Comment by tssajo** [comment] 2018-04-11 12:12
@kaste Thanks for the quick reply!

The funny thing is that despite the error, the linter works...

Do you want me to try the master of SublimeLinter or the master of SublimeLinter-gotype ? Or both ?

FYI, I have the following Go related SublimeLinter plugins installed:
```
SublimeLinter-golint
SublimeLinter-gotype
SublimeLinter-govet
```

I also have some other SublimeLinter plugins installed (e.g. for CSS, Javascript and PHP) but those seem to be working fine.

**Comment by kaste** [comment] 2018-04-11 12:26
Only SublimeLinter master. 

BrokenPipeError is not thrown synchronous but 'at some point' in python afaik. But the assumption is gotype closes stdin bc it does not expect data on stdin. 

(The 'nice' languages js, php, python are probably not affected bc they handle this automatically.?)
