### ISSUE TITLE
Mark styles are mixed. 

### ISSUE THREAD

**Issue by jtheletter** [SublimeLinter/SublimeLinter#1112] opened 2018-03-06 00:50 UTC
I prefer stippled underlines rather than outlines. So I added the following code to my `~/Library/Application Support/Sublime Text 3/Packages/User/SublimeLinter.sublime-settings` (the only change is to "mark_style"): 
```
    "styles": [
        {
            "mark_style": "stippled_underline",
            "priority": 1,
            "scope": "region.yellowish markup.changed.sublime_linter markup.warning.sublime_linter",
            "icon": "dot",
            "types": [
                "warning"
            ]
        },
        {
            "mark_style": "stippled_underline",
            "priority": 1,
            "scope": "region.redish markup.deleted.sublime_linter markup.error.sublime_linter",
            "icon": "dot",
            "types": [
                "error"
            ]
        }
    ]
```

The result is a mix of styles (solid underlines, stippled underlines, and outlines): 
![pic 2018-03-05 at 16 44 28](https://user-images.githubusercontent.com/4712441/37007994-e970c3e8-2094-11e8-88ac-fcb34e2748aa.png)

If I remove the above code from my user config, the styles revert to all being simply outlines: 
![pic 2018-03-05 at 16 45 20](https://user-images.githubusercontent.com/4712441/37008017-ffb0a1aa-2094-11e8-8a2c-4e59ceef9513.png)

Is this a bug, or am I configuring incorrectly? Thanks. 

SublimeLinter 4.0.2
Sublime Text 3.0
macOS 10.13.3

**Comment by eden-lane** [comment] 2018-03-06 09:11
I would like to disable outlines as well. Especially outlines for multiple lines

**Comment by braver** [comment] 2018-03-06 09:32
@eden-lane we have an issue open for that over at eslint: https://github.com/SublimeLinter/SublimeLinter-eslint/issues/212

**Comment by FichteFoll** [comment] 2018-03-06 12:40
Duplicate of #1105.

**Comment by braver** [comment] 2018-03-06 14:32
The settings now have a comment about this. It's intentional.

**Closed by braver** 2018-03-06 14:32 UTC
