### ISSUE TITLE
Gutter icon race condition

### ISSUE THREAD

**Issue by dndrsn** [SublimeLinter/SublimeLinter#1386] opened 2018-05-08 13:47 UTC
There appears to be a race condition that can cause Gitgutter icons to supersede the SublimeLinter icons.  I can make this happen just be typing a bunch of gibberish into lines that will register as a change in Gitgutter.  Anything that causes the the linter to reevaluate the file will fix the issue.

Not sure if this is a dupe of issue [#1302](https://github.com/SublimeLinter/SublimeLinter/issues/1302)

Using version 4.4.1

![image](https://user-images.githubusercontent.com/1944277/39760026-38ad0086-52a2-11e8-80a6-43a60f50644e.png)

![image](https://cl.ly/2m2T0R1Y3R43/download/Screen%20Recording%202018-05-08%20at%2009.39%20AM.gif)

![image](https://dzwonsemrish7.cloudfront.net/items/291E1f2U1v1v1d0Q291Y/Screen%20Recording%202018-05-08%20at%2009.35%20AM.gif)

**Comment by braver** [comment] 2018-05-08 15:41
I haven't seen that in a while. But it is inherently a bit of a race condition. We tell GitGutter to respect our icon and not override it, but I can totally imagine that the timing matters here, whether we draw first or GitGutter does. Also, the way Sublime Text renders these icons has seen some revisions in the last releases, so that might also come into play. I can't say much more about it than that it's fragile but seems to work ok most of the time on my machine. 🤷‍♂️

**Comment by kaste** [comment] 2018-05-08 18:40
This happens a lot. We would need full cooperation with GitGutter and other plugins to solve this. I don't think the code is the problem here.

**Comment by braver** [comment] 2018-05-08 18:44
@kaste That's certainly an option, people maintaining GitGutter have always been very willing to discuss and experiment with solutions.

**Comment by braver** [comment] 2019-03-26 19:59
Ok, so, basically we need to coordinate with other plugins that may want to have icons in the gutter, and we need to decide which one is more important, and then because icons can be added and removed at any time this causes race conditions. This can only reasonably be fixed by having a centralized gutter icon manager package, and deferring the actual drawing and updating of the icons to that manager. It could keep track of all packages that want to draw an icon on a certain position, prioritize them, and handle updates correctly. 

We only ever really interfaced with GitGutter here because it's a goldilocks package in that it's popular, actively maintained, and used in contexts where people tend to use linters and other functional feedback. There are others like BracketHighlighter and Color Highlighter, but apparently their users don't use linters a lot. 

Now, the GitGutter situation has actually been resolved by the new MiniDiff feature of SublimeLinter. GitGutter won't draw icons and leave that to MiniDiff. 

So, really, I don't think it's our problem to solve. It's a limitation in the ST API that could be solved by a community-wide effort to centralize the gutter icon management. I feel the problem isn't bad enough to warrant the effort. And I don't think it's necessarily up to the SublimeLinter group to spearhead this. So, while this area could be improved, this issue isn't where that will start, leaving this non-actionable and "won't fix" as far as SublimeLinter specifically is concerned.

**Closed by braver** 2019-03-26 19:59 UTC
