### ISSUE TITLE
Linter-specific settings are not discoverable.

### ISSUE THREAD

**Issue by FrankSalad** [SublimeLinter/SublimeLinter#1392] opened 2018-05-09 21:37 UTC
In Package Settings > SublimeLinter > Settings the user is presented with both the default settings and User settings in a split-pane window. The options available for configuration are presented in the left panel with commentary and documentation around them. 

<img width="721" alt="screen shot 2018-05-09 at 2 34 25 pm" src="https://user-images.githubusercontent.com/2359644/39840972-1cfbcd6e-5396-11e8-8664-6c3e5408c2a0.png">

Because SublimeLinter exposes a plugin mechanism, looking in the left panel is not sufficient for discovering what settings a plugin expects / exposes. The relevant part of the file does not lead the user in an actionable direction.

```
// Example of linter specific settings.
    // Linter specific settings can also be changed in sublime-project settings.
    // What settings are available is documented in the readme of the
    // specific linter plugin.
    // "linters": {
    //     "somelinter": {
    //         "disable": false,
    //         "args": [],
    //         "excludes": []
    //     },
    //     "somepythonlinter": {
    //         "python": null,
    //         "disable": false,
    //         "args": [
    //             "--max-complexity", "-1",
    //             "--max-line-length", "100",
    //             "--ignore", "E731,E402"
    //         ],
    //         "excludes": [],
    //     }
    // }
```

Questions left open after reading this description: 

- What plugins do I have installed?
- Which plugin is causing SublimeLinter to behave a certain way?
- How do I find where the plugin readme is stored?

An ideal solution would be to have plugins append to this file their specific set of expected parameters. An interrim solution would be to have answers for these open questions in this section.

**Comment by kaste** [comment] 2018-05-09 21:48
That's a very good point.

**Comment by braver** [comment] 2018-05-10 05:43
> An ideal solution would be to have plugins append to this file their specific set of expected parameters.

That’s not possible AFAIK, the default settings cannot be written to. Not necessarily the best solution either.

> An interrim solution would be to have answers for these open questions in this section.

That’s a good idea. All of those things are easily explained and users should probably refer to the readme’s anyway.

**Comment by kaste** [comment] 2018-05-10 13:38
A showcase command for opening README's can be found here https://github.com/kaste/SublimeLinter-addon-metainfo (ST 3.1 required)

**Comment by braver** [comment] 2018-05-11 08:57
This one also probably works: https://packagecontrol.io/packages/ReadmePlease

**Comment by kaste** [comment] 2018-05-11 13:46
More interesting would be if the plugins had more docs, but they don't. E.g. we could read `cls.__doc__` programmatically, but no plugin has useful documentation here. Also plugins define

```
cls.defaults = {
	'--some-arg': 'someDefault',
	'--config-file': ''
}
```

And we can of course, read that out. But we don't have any docstrings (or type info) here as well.

**Comment by braver** [comment] 2018-08-27 08:16
> More interesting would be if the plugins had more docs, but they don't

Also, they shouldn't. We should be moving towards a situation where linters all have the same settings: args env and one or two others. Then the standard docs already cover them. 
I'm not enthusiastic about building extra support around linter specific settings.

**Comment by braver** [comment] 2018-12-16 19:18
Some further thoughts:

- most linters don't have special settings
- most of those that do can drop them because SL now has filtering built in
- special settings per linter aren't encouraged, it's very rare that they expose something not already covered by args or other settings, usually they merely attempt to make those settings "easier"
- the discoverability of documentation isn't a SublimeLinter specific problem

As to point in the the OP:

>  What plugins do I have installed?

You should be aware of the plugins you have installed (you're the one who installed them), package control can list them if you forgot.

> Which plugin is causing SublimeLinter to behave a certain way?

The impact on behavior should be pretty limited, especially if you haven't changed settings from their defaults. If you want to find out more, reading the settings file usually isn't the most effective place to start. 

> How do I find where the plugin readme is stored?

All packages have the same problems. How do you know what they can do? You find their repo or entry in packagecontro.io and you look it up.

So, the issue isn't invalid, and linter settings could be more easily discovered. It is at the same time not a big problem, we don't get reports from people that don't know where to find stuff. If someone has a great idea and starts a PR, that's always welcome. But I don't think this will ever find its way onto our roadmap, so I'm not going to keep this open.

**Closed by braver** 2018-12-16 19:18 UTC
Labels: actionable, enhancement, good first issue
