### ISSUE TITLE
Unable to read Packages/SublimeLinter/panel/panel.sublime-syntax

### ISSUE THREAD

**Issue by Gabriel-p** [SublimeLinter/SublimeLinter#1144] opened 2018-03-06 23:40 UTC
This is related to #1122 except I have not uninstalled `SublimeLinter`. I have v4.0.5 installed (ST3 v3.0 Build 3143) and the full message is:

> Error loading syntax file "Packages/SublimeLinter/panel/panel.sublime-syntax": Unable to read Packages/SublimeLinter/panel/panel.sublime-syntax

and it shows almost every time I open ST3, as soon as it loads.

**Comment by FichteFoll** [comment] 2018-03-06 23:56
Duplicate of #1122.

**Closed** 2018-03-07 08:55 UTC
