### ISSUE TITLE
Reloader goes haywire

### ISSUE THREAD

**Issue by braver** [SublimeLinter/SublimeLinter#1388] opened 2018-05-09 12:59 UTC
@kaste I just tried an upgrade from 4.4.1 to 4.5.0 via package control. Below what I see in the console...

It reloads every plugin 29 times.

I've seen a report of an upgrade crashing ST, so that may be related.

```reloading plugin SublimeLinter.__init__
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 116, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
zipimport.ZipImportError: bad local file header in /Users/koenlageveen/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package
reloading plugin SublimeLinter.active_linters_view
reloading plugin SublimeLinter.busy_indicator_view
reloading plugin SublimeLinter.goto_commands
reloading plugin SublimeLinter.highlight_view
reloading plugin SublimeLinter.log_handler
reloading plugin SublimeLinter.message_view
reloading plugin SublimeLinter.panel_view
reloading plugin SublimeLinter.status_bar_view
reloading plugin SublimeLinter.sublime_linter
reloading settings Packages/SublimeLinter/SublimeLinter.sublime-settings
generating syntax summary
reloading plugin SublimeLinter.lint
reloading plugin SublimeLinter.active_linters_view
reloading plugin SublimeLinter.busy_indicator_view
reloading plugin SublimeLinter.goto_commands
reloading plugin SublimeLinter.highlight_view
reloading plugin SublimeLinter.lint
reloading plugin SublimeLinter.log_handler
reloading plugin SublimeLinter.message_view
reloading plugin SublimeLinter.panel_view
reloading plugin SublimeLinter.status_bar_view
reloading plugin SublimeLinter.sublime_linter
reloading plugin SublimeLinter-annotations.linter
reloading plugin SublimeLinter-eslint.linter
reloading plugin SublimeLinter-flake8.linter
reloading plugin SublimeLinter-html-tidy.linter
reloading plugin SublimeLinter-json.linter
reloading plugin SublimeLinter-pydocstyle.linter
reloading plugin SublimeLinter-shellcheck.linter
reloading plugin SublimeLinter-stylelint.linter
reloading plugin SublimeLinter-tslint.linter
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading plugin SublimeLinter.lint
reloading plugin SublimeLinter.active_linters_view
reloading plugin SublimeLinter.busy_indicator_view
reloading plugin SublimeLinter.goto_commands
reloading plugin SublimeLinter.highlight_view
reloading plugin SublimeLinter.lint
reloading plugin SublimeLinter.log_handler
reloading plugin SublimeLinter.message_view
reloading plugin SublimeLinter.panel_view
reloading plugin SublimeLinter.status_bar_view
reloading plugin SublimeLinter.sublime_linter
reloading plugin SublimeLinter-annotations.linter
reloading plugin SublimeLinter-eslint.linter
reloading plugin SublimeLinter-flake8.linter
reloading plugin SublimeLinter-html-tidy.linter
reloading plugin SublimeLinter-json.linter
reloading plugin SublimeLinter-pydocstyle.linter
reloading plugin SublimeLinter-shellcheck.linter
reloading plugin SublimeLinter-stylelint.linter
reloading plugin SublimeLinter-tslint.linter
reloading plugin SublimeLinter.lint
reloading plugin SublimeLinter.active_linters_view
reloading plugin SublimeLinter.busy_indicator_view
reloading plugin SublimeLinter.goto_commands
reloading plugin SublimeLinter.highlight_view
reloading plugin SublimeLinter.lint
reloading plugin SublimeLinter.log_handler
reloading plugin SublimeLinter.message_view
reloading plugin SublimeLinter.panel_view
reloading plugin SublimeLinter.status_bar_view
reloading plugin SublimeLinter.sublime_linter
reloading plugin SublimeLinter-annotations.linter
reloading plugin SublimeLinter-eslint.linter
reloading plugin SublimeLinter-flake8.linter
reloading plugin SublimeLinter-html-tidy.linter
reloading plugin SublimeLinter-json.linter
reloading plugin SublimeLinter-pydocstyle.linter
reloading plugin SublimeLinter-shellcheck.linter
reloading plugin SublimeLinter-stylelint.linter
reloading plugin SublimeLinter-tslint.linter
reloading plugin SublimeLinter.lint
reloading plugin SublimeLinter.active_linters_view
reloading plugin SublimeLinter.busy_indicator_view
reloading plugin SublimeLinter.goto_commands
reloading plugin SublimeLinter.highlight_view
reloading plugin SublimeLinter.lint
reloading plugin SublimeLinter.log_handler
reloading plugin SublimeLinter.message_view
reloading plugin SublimeLinter.panel_view
reloading plugin SublimeLinter.status_bar_view
reloading plugin SublimeLinter.sublime_linter
reloading plugin SublimeLinter-annotations.linter
reloading plugin SublimeLinter-eslint.linter
reloading plugin SublimeLinter-flake8.linter
reloading plugin SublimeLinter-html-tidy.linter
reloading plugin SublimeLinter-json.linter
reloading plugin SublimeLinter-pydocstyle.linter
reloading plugin SublimeLinter-shellcheck.linter
reloading plugin SublimeLinter-stylelint.linter
reloading plugin SublimeLinter-tslint.linter
reloading plugin SublimeLinter.lint
reloading plugin SublimeLinter.active_linters_view
reloading plugin SublimeLinter.busy_indicator_view
reloading plugin SublimeLinter.goto_commands
reloading plugin SublimeLinter.highlight_view
reloading plugin SublimeLinter.lint
reloading plugin SublimeLinter.log_handler
reloading plugin SublimeLinter.message_view
reloading plugin SublimeLinter.panel_view
reloading plugin SublimeLinter.status_bar_view
reloading plugin SublimeLinter.sublime_linter
reloading plugin SublimeLinter-annotations.linter
reloading plugin SublimeLinter-eslint.linter
reloading plugin SublimeLinter-flake8.linter
reloading plugin SublimeLinter-html-tidy.linter
reloading plugin SublimeLinter-json.linter
reloading plugin SublimeLinter-pydocstyle.linter
reloading plugin SublimeLinter-shellcheck.linter
reloading plugin SublimeLinter-stylelint.linter
reloading plugin SublimeLinter-tslint.linter
reloading plugin SublimeLinter.lint
reloading plugin SublimeLinter.active_linters_view
reloading plugin SublimeLinter.busy_indicator_view
reloading plugin SublimeLinter.goto_commands
reloading plugin SublimeLinter.highlight_view
reloading plugin SublimeLinter.lint
reloading plugin SublimeLinter.log_handler
reloading plugin SublimeLinter.message_view
reloading plugin SublimeLinter.panel_view
reloading plugin SublimeLinter.status_bar_view
reloading plugin SublimeLinter.sublime_linter
reloading plugin SublimeLinter-annotations.linter
reloading plugin SublimeLinter-eslint.linter
reloading plugin SublimeLinter-flake8.linter
reloading plugin SublimeLinter-html-tidy.linter
reloading plugin SublimeLinter-json.linter
reloading plugin SublimeLinter-pydocstyle.linter
reloading plugin SublimeLinter-shellcheck.linter
reloading plugin SublimeLinter-stylelint.linter
reloading plugin SublimeLinter-tslint.linter
reloading plugin SublimeLinter.lint
reloading plugin SublimeLinter.active_linters_view
reloading plugin SublimeLinter.busy_indicator_view
reloading plugin SublimeLinter.goto_commands
reloading plugin SublimeLinter.highlight_view
reloading plugin SublimeLinter.lint
reloading plugin SublimeLinter.log_handler
reloading plugin SublimeLinter.message_view
reloading plugin SublimeLinter.panel_view
reloading plugin SublimeLinter.status_bar_view
reloading plugin SublimeLinter.sublime_linter
reloading plugin SublimeLinter-annotations.linter
reloading plugin SublimeLinter-eslint.linter
reloading plugin SublimeLinter-flake8.linter
reloading plugin SublimeLinter-html-tidy.linter
reloading plugin SublimeLinter-json.linter
reloading plugin SublimeLinter-pydocstyle.linter
reloading plugin SublimeLinter-shellcheck.linter
reloading plugin SublimeLinter-stylelint.linter
reloading plugin SublimeLinter-tslint.linter
reloading settings Packages/User/Preferences.sublime-settings
reloading plugin SublimeLinter.lint
reloading plugin SublimeLinter.active_linters_view
reloading plugin SublimeLinter.busy_indicator_view
reloading plugin SublimeLinter.goto_commands
reloading plugin SublimeLinter.highlight_view
reloading plugin SublimeLinter.lint
reloading plugin SublimeLinter.log_handler
reloading plugin SublimeLinter.message_view
reloading plugin SublimeLinter.panel_view
reloading plugin SublimeLinter.status_bar_view
reloading plugin SublimeLinter.sublime_linter
reloading plugin SublimeLinter-annotations.linter
reloading plugin SublimeLinter-eslint.linter
reloading plugin SublimeLinter-flake8.linter
reloading plugin SublimeLinter-html-tidy.linter
reloading plugin SublimeLinter-json.linter
reloading plugin SublimeLinter-pydocstyle.linter
reloading plugin SublimeLinter-shellcheck.linter
reloading plugin SublimeLinter-stylelint.linter
reloading plugin SublimeLinter-tslint.linter
reloading plugin SublimeLinter.lint
reloading plugin SublimeLinter.active_linters_view
reloading plugin SublimeLinter.busy_indicator_view
reloading plugin SublimeLinter.goto_commands
reloading plugin SublimeLinter.highlight_view
reloading plugin SublimeLinter.lint
reloading plugin SublimeLinter.log_handler
reloading plugin SublimeLinter.message_view
reloading plugin SublimeLinter.panel_view
reloading plugin SublimeLinter.status_bar_view
reloading plugin SublimeLinter.sublime_linter
reloading plugin SublimeLinter-annotations.linter
reloading plugin SublimeLinter-eslint.linter
reloading plugin SublimeLinter-flake8.linter
reloading plugin SublimeLinter-html-tidy.linter
reloading plugin SublimeLinter-json.linter
reloading plugin SublimeLinter-pydocstyle.linter
reloading plugin SublimeLinter-shellcheck.linter
reloading plugin SublimeLinter-stylelint.linter
reloading plugin SublimeLinter-tslint.linter
reloading plugin SublimeLinter.lint
reloading plugin SublimeLinter.active_linters_view
reloading plugin SublimeLinter.busy_indicator_view
reloading plugin SublimeLinter.goto_commands
reloading plugin SublimeLinter.highlight_view
reloading plugin SublimeLinter.lint
reloading plugin SublimeLinter.log_handler
reloading plugin SublimeLinter.message_view
reloading plugin SublimeLinter.panel_view
reloading plugin SublimeLinter.status_bar_view
reloading plugin SublimeLinter.sublime_linter
reloading plugin SublimeLinter-annotations.linter
reloading plugin SublimeLinter-eslint.linter
reloading plugin SublimeLinter-flake8.linter
reloading plugin SublimeLinter-html-tidy.linter
reloading plugin SublimeLinter-json.linter
reloading plugin SublimeLinter-pydocstyle.linter
reloading plugin SublimeLinter-shellcheck.linter
reloading plugin SublimeLinter-stylelint.linter
reloading plugin SublimeLinter-tslint.linter
reloading plugin SublimeLinter.lint
reloading plugin SublimeLinter.active_linters_view
reloading plugin SublimeLinter.busy_indicator_view
reloading plugin SublimeLinter.goto_commands
reloading plugin SublimeLinter.highlight_view
reloading plugin SublimeLinter.lint
reloading plugin SublimeLinter.log_handler
reloading plugin SublimeLinter.message_view
reloading plugin SublimeLinter.panel_view
reloading plugin SublimeLinter.status_bar_view
reloading plugin SublimeLinter.sublime_linter
reloading plugin SublimeLinter-annotations.linter
reloading plugin SublimeLinter-eslint.linter
reloading plugin SublimeLinter-flake8.linter
reloading plugin SublimeLinter-html-tidy.linter
reloading plugin SublimeLinter-json.linter
reloading plugin SublimeLinter-pydocstyle.linter
reloading plugin SublimeLinter-shellcheck.linter
reloading plugin SublimeLinter-stylelint.linter
reloading plugin SublimeLinter-tslint.linter
reloading plugin SublimeLinter.lint
reloading plugin SublimeLinter.active_linters_view
reloading plugin SublimeLinter.busy_indicator_view
reloading plugin SublimeLinter.goto_commands
reloading plugin SublimeLinter.highlight_view
reloading plugin SublimeLinter.lint
reloading plugin SublimeLinter.log_handler
reloading plugin SublimeLinter.message_view
reloading plugin SublimeLinter.panel_view
reloading plugin SublimeLinter.status_bar_view
reloading plugin SublimeLinter.sublime_linter
reloading plugin SublimeLinter-annotations.linter
reloading plugin SublimeLinter-eslint.linter
reloading plugin SublimeLinter-flake8.linter
reloading plugin SublimeLinter-html-tidy.linter
reloading plugin SublimeLinter-json.linter
reloading plugin SublimeLinter-pydocstyle.linter
reloading plugin SublimeLinter-shellcheck.linter
reloading plugin SublimeLinter-stylelint.linter
reloading plugin SublimeLinter-tslint.linter
reloading plugin SublimeLinter.lint
reloading plugin SublimeLinter.active_linters_view
reloading plugin SublimeLinter.busy_indicator_view
reloading plugin SublimeLinter.goto_commands
reloading plugin SublimeLinter.highlight_view
reloading plugin SublimeLinter.lint
reloading plugin SublimeLinter.log_handler
reloading plugin SublimeLinter.message_view
reloading plugin SublimeLinter.panel_view
reloading plugin SublimeLinter.status_bar_view
reloading plugin SublimeLinter.sublime_linter
reloading plugin SublimeLinter-annotations.linter
reloading plugin SublimeLinter-eslint.linter
reloading plugin SublimeLinter-flake8.linter
reloading plugin SublimeLinter-html-tidy.linter
reloading plugin SublimeLinter-json.linter
reloading plugin SublimeLinter-pydocstyle.linter
reloading plugin SublimeLinter-shellcheck.linter
reloading plugin SublimeLinter-stylelint.linter
reloading plugin SublimeLinter-tslint.linter
reloading plugin SublimeLinter.lint
reloading plugin SublimeLinter.active_linters_view
reloading plugin SublimeLinter.busy_indicator_view
reloading plugin SublimeLinter.goto_commands
reloading plugin SublimeLinter.highlight_view
reloading plugin SublimeLinter.lint
reloading plugin SublimeLinter.log_handler
reloading plugin SublimeLinter.message_view
reloading plugin SublimeLinter.panel_view
reloading plugin SublimeLinter.status_bar_view
reloading plugin SublimeLinter.sublime_linter
reloading plugin SublimeLinter-annotations.linter
reloading plugin SublimeLinter-eslint.linter
reloading plugin SublimeLinter-flake8.linter
reloading plugin SublimeLinter-html-tidy.linter
reloading plugin SublimeLinter-json.linter
reloading plugin SublimeLinter-pydocstyle.linter
reloading plugin SublimeLinter-shellcheck.linter
reloading plugin SublimeLinter-stylelint.linter
reloading plugin SublimeLinter-tslint.linter
reloading plugin SublimeLinter.lint
reloading plugin SublimeLinter.active_linters_view
reloading plugin SublimeLinter.busy_indicator_view
reloading plugin SublimeLinter.goto_commands
reloading plugin SublimeLinter.highlight_view
reloading plugin SublimeLinter.lint
reloading plugin SublimeLinter.log_handler
reloading plugin SublimeLinter.message_view
reloading plugin SublimeLinter.panel_view
reloading plugin SublimeLinter.status_bar_view
reloading plugin SublimeLinter.sublime_linter
reloading plugin SublimeLinter-annotations.linter
reloading plugin SublimeLinter-eslint.linter
reloading plugin SublimeLinter-flake8.linter
reloading plugin SublimeLinter-html-tidy.linter
reloading plugin SublimeLinter-json.linter
reloading plugin SublimeLinter-pydocstyle.linter
reloading plugin SublimeLinter-shellcheck.linter
reloading plugin SublimeLinter-stylelint.linter
reloading plugin SublimeLinter-tslint.linter
reloading plugin SublimeLinter.lint
reloading plugin SublimeLinter.active_linters_view
reloading plugin SublimeLinter.busy_indicator_view
reloading plugin SublimeLinter.goto_commands
reloading plugin SublimeLinter.highlight_view
reloading plugin SublimeLinter.lint
reloading plugin SublimeLinter.log_handler
reloading plugin SublimeLinter.message_view
reloading plugin SublimeLinter.panel_view
reloading plugin SublimeLinter.status_bar_view
reloading plugin SublimeLinter.sublime_linter
reloading plugin SublimeLinter-annotations.linter
reloading plugin SublimeLinter-eslint.linter
reloading plugin SublimeLinter-flake8.linter
reloading plugin SublimeLinter-html-tidy.linter
reloading plugin SublimeLinter-json.linter
reloading plugin SublimeLinter-pydocstyle.linter
reloading plugin SublimeLinter-shellcheck.linter
reloading plugin SublimeLinter-stylelint.linter
reloading plugin SublimeLinter-tslint.linter
reloading plugin SublimeLinter.lint
reloading plugin SublimeLinter.active_linters_view
reloading plugin SublimeLinter.busy_indicator_view
reloading plugin SublimeLinter.goto_commands
reloading plugin SublimeLinter.highlight_view
reloading plugin SublimeLinter.lint
reloading plugin SublimeLinter.log_handler
reloading plugin SublimeLinter.message_view
reloading plugin SublimeLinter.panel_view
reloading plugin SublimeLinter.status_bar_view
reloading plugin SublimeLinter.sublime_linter
reloading plugin SublimeLinter-annotations.linter
reloading plugin SublimeLinter-eslint.linter
reloading plugin SublimeLinter-flake8.linter
reloading plugin SublimeLinter-html-tidy.linter
reloading plugin SublimeLinter-json.linter
reloading plugin SublimeLinter-pydocstyle.linter
reloading plugin SublimeLinter-shellcheck.linter
reloading plugin SublimeLinter-stylelint.linter
reloading plugin SublimeLinter-tslint.linter
reloading plugin SublimeLinter.lint
reloading plugin SublimeLinter.active_linters_view
reloading plugin SublimeLinter.busy_indicator_view
reloading plugin SublimeLinter.goto_commands
reloading plugin SublimeLinter.highlight_view
reloading plugin SublimeLinter.lint
reloading plugin SublimeLinter.log_handler
reloading plugin SublimeLinter.message_view
reloading plugin SublimeLinter.panel_view
reloading plugin SublimeLinter.status_bar_view
reloading plugin SublimeLinter.sublime_linter
reloading plugin SublimeLinter-annotations.linter
reloading plugin SublimeLinter-eslint.linter
reloading plugin SublimeLinter-flake8.linter
reloading plugin SublimeLinter-html-tidy.linter
reloading plugin SublimeLinter-json.linter
reloading plugin SublimeLinter-pydocstyle.linter
reloading plugin SublimeLinter-shellcheck.linter
reloading plugin SublimeLinter-stylelint.linter
reloading plugin SublimeLinter-tslint.linter
reloading plugin SublimeLinter.lint
reloading plugin SublimeLinter.active_linters_view
reloading plugin SublimeLinter.busy_indicator_view
reloading plugin SublimeLinter.goto_commands
reloading plugin SublimeLinter.highlight_view
reloading plugin SublimeLinter.lint
reloading plugin SublimeLinter.log_handler
reloading plugin SublimeLinter.message_view
reloading plugin SublimeLinter.panel_view
reloading plugin SublimeLinter.status_bar_view
reloading plugin SublimeLinter.sublime_linter
reloading plugin SublimeLinter-annotations.linter
reloading plugin SublimeLinter-eslint.linter
reloading plugin SublimeLinter-flake8.linter
reloading plugin SublimeLinter-html-tidy.linter
reloading plugin SublimeLinter-json.linter
reloading plugin SublimeLinter-pydocstyle.linter
reloading plugin SublimeLinter-shellcheck.linter
reloading plugin SublimeLinter-stylelint.linter
reloading plugin SublimeLinter-tslint.linter
reloading plugin SublimeLinter.lint
reloading plugin SublimeLinter.active_linters_view
reloading plugin SublimeLinter.busy_indicator_view
reloading plugin SublimeLinter.goto_commands
reloading plugin SublimeLinter.highlight_view
reloading plugin SublimeLinter.lint
reloading plugin SublimeLinter.log_handler
reloading plugin SublimeLinter.message_view
reloading plugin SublimeLinter.panel_view
reloading plugin SublimeLinter.status_bar_view
reloading plugin SublimeLinter.sublime_linter
reloading plugin SublimeLinter-annotations.linter
reloading plugin SublimeLinter-eslint.linter
reloading plugin SublimeLinter-flake8.linter
reloading plugin SublimeLinter-html-tidy.linter
reloading plugin SublimeLinter-json.linter
reloading plugin SublimeLinter-pydocstyle.linter
reloading plugin SublimeLinter-shellcheck.linter
reloading plugin SublimeLinter-stylelint.linter
reloading plugin SublimeLinter-tslint.linter
reloading plugin SublimeLinter.lint
reloading plugin SublimeLinter.active_linters_view
reloading plugin SublimeLinter.busy_indicator_view
reloading plugin SublimeLinter.goto_commands
reloading plugin SublimeLinter.highlight_view
reloading plugin SublimeLinter.lint
reloading plugin SublimeLinter.log_handler
reloading plugin SublimeLinter.message_view
reloading plugin SublimeLinter.panel_view
reloading plugin SublimeLinter.status_bar_view
reloading plugin SublimeLinter.sublime_linter
reloading plugin SublimeLinter-annotations.linter
reloading plugin SublimeLinter-eslint.linter
reloading plugin SublimeLinter-flake8.linter
reloading plugin SublimeLinter-html-tidy.linter
reloading plugin SublimeLinter-json.linter
reloading plugin SublimeLinter-pydocstyle.linter
reloading plugin SublimeLinter-shellcheck.linter
reloading plugin SublimeLinter-stylelint.linter
reloading plugin SublimeLinter-tslint.linter
reloading plugin SublimeLinter.lint
reloading plugin SublimeLinter.active_linters_view
reloading plugin SublimeLinter.busy_indicator_view
reloading plugin SublimeLinter.goto_commands
reloading plugin SublimeLinter.highlight_view
reloading plugin SublimeLinter.lint
reloading plugin SublimeLinter.log_handler
reloading plugin SublimeLinter.message_view
reloading plugin SublimeLinter.panel_view
reloading plugin SublimeLinter.status_bar_view
reloading plugin SublimeLinter.sublime_linter
reloading plugin SublimeLinter-annotations.linter
reloading plugin SublimeLinter-eslint.linter
reloading plugin SublimeLinter-flake8.linter
reloading plugin SublimeLinter-html-tidy.linter
reloading plugin SublimeLinter-json.linter
reloading plugin SublimeLinter-pydocstyle.linter
reloading plugin SublimeLinter-shellcheck.linter
reloading plugin SublimeLinter-stylelint.linter
reloading plugin SublimeLinter-tslint.linter
reloading plugin SublimeLinter.lint
reloading plugin SublimeLinter.active_linters_view
reloading plugin SublimeLinter.busy_indicator_view
reloading plugin SublimeLinter.goto_commands
reloading plugin SublimeLinter.highlight_view
reloading plugin SublimeLinter.lint
reloading plugin SublimeLinter.log_handler
reloading plugin SublimeLinter.message_view
reloading plugin SublimeLinter.panel_view
reloading plugin SublimeLinter.status_bar_view
reloading plugin SublimeLinter.sublime_linter
reloading plugin SublimeLinter-annotations.linter
reloading plugin SublimeLinter-eslint.linter
reloading plugin SublimeLinter-flake8.linter
reloading plugin SublimeLinter-html-tidy.linter
reloading plugin SublimeLinter-json.linter
reloading plugin SublimeLinter-pydocstyle.linter
reloading plugin SublimeLinter-shellcheck.linter
reloading plugin SublimeLinter-stylelint.linter
reloading plugin SublimeLinter-tslint.linter
reloading plugin SublimeLinter.lint
reloading plugin SublimeLinter.active_linters_view
reloading plugin SublimeLinter.busy_indicator_view
reloading plugin SublimeLinter.goto_commands
reloading plugin SublimeLinter.highlight_view
reloading plugin SublimeLinter.lint
reloading plugin SublimeLinter.log_handler
reloading plugin SublimeLinter.message_view
reloading plugin SublimeLinter.panel_view
reloading plugin SublimeLinter.status_bar_view
reloading plugin SublimeLinter.sublime_linter
reloading plugin SublimeLinter-annotations.linter
reloading plugin SublimeLinter-eslint.linter
reloading plugin SublimeLinter-flake8.linter
reloading plugin SublimeLinter-html-tidy.linter
reloading plugin SublimeLinter-json.linter
reloading plugin SublimeLinter-pydocstyle.linter
reloading plugin SublimeLinter-shellcheck.linter
reloading plugin SublimeLinter-stylelint.linter
reloading plugin SublimeLinter-tslint.linter
reloading plugin SublimeLinter.lint
reloading plugin SublimeLinter.active_linters_view
reloading plugin SublimeLinter.busy_indicator_view
reloading plugin SublimeLinter.goto_commands
reloading plugin SublimeLinter.highlight_view
reloading plugin SublimeLinter.lint
reloading plugin SublimeLinter.log_handler
reloading plugin SublimeLinter.message_view
reloading plugin SublimeLinter.panel_view
reloading plugin SublimeLinter.status_bar_view
reloading plugin SublimeLinter.sublime_linter
reloading plugin SublimeLinter-annotations.linter
reloading plugin SublimeLinter-eslint.linter
reloading plugin SublimeLinter-flake8.linter
reloading plugin SublimeLinter-html-tidy.linter
reloading plugin SublimeLinter-json.linter
reloading plugin SublimeLinter-pydocstyle.linter
reloading plugin SublimeLinter-shellcheck.linter
reloading plugin SublimeLinter-stylelint.linter
reloading plugin SublimeLinter-tslint.linter
reloading plugin SublimeLinter.lint
reloading plugin SublimeLinter.active_linters_view
reloading plugin SublimeLinter.busy_indicator_view
reloading plugin SublimeLinter.goto_commands
reloading plugin SublimeLinter.highlight_view
reloading plugin SublimeLinter.lint
reloading plugin SublimeLinter.log_handler
reloading plugin SublimeLinter.message_view
reloading plugin SublimeLinter.panel_view
reloading plugin SublimeLinter.status_bar_view
reloading plugin SublimeLinter.sublime_linter
reloading plugin SublimeLinter-annotations.linter
reloading plugin SublimeLinter-eslint.linter
reloading plugin SublimeLinter-flake8.linter
reloading plugin SublimeLinter-html-tidy.linter
reloading plugin SublimeLinter-json.linter
reloading plugin SublimeLinter-pydocstyle.linter
reloading plugin SublimeLinter-shellcheck.linter
reloading plugin SublimeLinter-stylelint.linter
reloading plugin SublimeLinter-tslint.linter
reloading plugin SublimeLinter.lint
reloading plugin SublimeLinter.active_linters_view
reloading plugin SublimeLinter.busy_indicator_view
reloading plugin SublimeLinter.goto_commands
reloading plugin SublimeLinter.highlight_view
reloading plugin SublimeLinter.lint
reloading plugin SublimeLinter.log_handler
reloading plugin SublimeLinter.message_view
reloading plugin SublimeLinter.panel_view
reloading plugin SublimeLinter.status_bar_view
reloading plugin SublimeLinter.sublime_linter
reloading plugin SublimeLinter-annotations.linter
reloading plugin SublimeLinter-eslint.linter
reloading plugin SublimeLinter-flake8.linter
reloading plugin SublimeLinter-html-tidy.linter
reloading plugin SublimeLinter-json.linter
reloading plugin SublimeLinter-pydocstyle.linter
reloading plugin SublimeLinter-shellcheck.linter
reloading plugin SublimeLinter-stylelint.linter
reloading plugin SublimeLinter-tslint.linter
reloading plugin SublimeLinter.lint
reloading plugin SublimeLinter.active_linters_view
reloading plugin SublimeLinter.busy_indicator_view
reloading plugin SublimeLinter.goto_commands
reloading plugin SublimeLinter.highlight_view
reloading plugin SublimeLinter.lint
reloading plugin SublimeLinter.log_handler
reloading plugin SublimeLinter.message_view
reloading plugin SublimeLinter.panel_view
reloading plugin SublimeLinter.status_bar_view
reloading plugin SublimeLinter.sublime_linter
reloading plugin SublimeLinter-annotations.linter
reloading plugin SublimeLinter-eslint.linter
reloading plugin SublimeLinter-flake8.linter
reloading plugin SublimeLinter-html-tidy.linter
reloading plugin SublimeLinter-json.linter
reloading plugin SublimeLinter-pydocstyle.linter
reloading plugin SublimeLinter-shellcheck.linter
reloading plugin SublimeLinter-stylelint.linter
reloading plugin SublimeLinter-tslint.linter
reloading plugin SublimeLinter.lint
reloading plugin SublimeLinter.active_linters_view
reloading plugin SublimeLinter.busy_indicator_view
reloading plugin SublimeLinter.goto_commands
reloading plugin SublimeLinter.highlight_view
reloading plugin SublimeLinter.lint
reloading plugin SublimeLinter.log_handler
reloading plugin SublimeLinter.message_view
reloading plugin SublimeLinter.panel_view
reloading plugin SublimeLinter.status_bar_view
reloading plugin SublimeLinter.sublime_linter
reloading plugin SublimeLinter-annotations.linter
reloading plugin SublimeLinter-eslint.linter
reloading plugin SublimeLinter-flake8.linter
reloading plugin SublimeLinter-html-tidy.linter
reloading plugin SublimeLinter-json.linter
reloading plugin SublimeLinter-pydocstyle.linter
reloading plugin SublimeLinter-shellcheck.linter
reloading plugin SublimeLinter-stylelint.linter
reloading plugin SublimeLinter-tslint.linter
```

**Comment by kaste** [comment] 2018-05-09 14:07
Did you count that by hand. Just asking.

**Comment by braver** [comment] 2018-05-09 14:12
Yes of course. 

By hand I copied that to a new view, selected `reloading plugin SublimeLinter-pydocstyle.linter` and hit `CMD+F` to let ST report the number of hits 😉

**Comment by kaste** [comment] 2018-05-09 14:28
Can we secretly delete this issue so that nobody knows that I REALLY WANTED THAT HOT-RELOADING NO MATTER WHAT.

**Comment by braver** [comment] 2018-05-09 14:29
Well, it cannot be said that it doesn't reload.

**Comment by kaste** [comment] 2018-05-09 14:31
Well, I could assign this issue to you.

**Comment by kaste** [comment] 2018-05-09 14:31
Ok, now I'm feeling better.

**Comment by braver** [comment] 2018-05-09 14:32
Well, that may end up with me removing the reloader, so be careful what you ask for here.

**Comment by kaste** [comment] 2018-05-09 14:33
Shhh, we close as Works As Intended:tm:

**Comment by braver** [comment] 2018-05-09 14:34
🤣

**Comment by kaste** [comment] 2018-05-09 14:38
Otherwise, we could label as enhancement and 'good first issue'.

**Comment by kaste** [comment] 2018-05-09 15:35
Okay, what's going on here.

Package Control sets an event `install/upgrade`. This is a misnomer of course, it is a flag. An event, you consume and then react, but the event is gone. 

Anyway, the flag is set. We defer a `reload`. The reload itself is as fast as your computer is. But the flag is still set, so we ... recurse.

Until Package Control unsets the flag. Then we're okay.

**Comment by braver** [comment] 2018-05-09 16:03
Ehm ok, but there is no need to loop on our end right? Just respond to the “event” once and be done with it?

**Comment by kaste** [comment] 2018-05-09 17:34
Just ask wbond how long this flag is set or read the source code (lol), then we debounce for that time.

I don't know if it is better to reload multiple times though.

**Comment by kaste** [comment] 2018-05-09 18:05
Well, I read the source code. It's 5(!) seconds.

https://github.com/wbond/package_control/blob/ea2c658bf48ded502c2619af3aa70e86dcd2cd00/package_control/events.py#L66

**Comment by kaste** [comment] 2018-05-09 18:35
You can still ask wbond, you run 29 reloads here, so one load is under 100ms actually.

**Closed** 2018-05-11 09:56 UTC
Labels: enhancement, has PR
