### ISSUE TITLE
Beachballing in Sublime Text 3 on Mac M1 processors

### ISSUE THREAD

**Issue by TehShrike** [SublimeLinter/SublimeLinter#1787] opened 2021-04-12 15:20 UTC
I am one of several people who have run into issues with Sublime Text 3 on macOS 11.1+.  SublimeLinter + M1 processors seem to be the common denominators.

`plugin_host` regularly locks up with 90%+ CPU utilization, beachballing Sublime Text.

https://forum.sublimetext.com/t/st3-crashes-constantly-with-osx-11-1-beta-20c5048k/55031/37

**Comment by kaste** [comment] 2021-04-12 19:30
Ok.  Maybe someone can attach a debugger to the plugin_host at some point.  (Esp. when you only need a M1 plus clang.)  

In the thread, I read *eslint* and *clang* as being catastrophic, and *cpplint* as a bit better.  The difference between both is that the former use stdin-out pipes, the later analyzes (temporary) files (on disk).  

The difference between "on save" and "background" linting is probably a) how often a linter runs and b) how often we (try to) abort a running subprocess.

Out of curiosity, how many threads do we actually use here?  https://github.com/SublimeLinter/SublimeLinter/blob/35a7afe930d9fc8d3e5acc523bfef8a4f21a8256/lint/backend.py#L31-L31

Is this still a sane value on the M1 procs? 

We have the switch "kill_old_processes" which you could set to `false` in your settings.  (Then we don't kill any processes, which is a waste but maybe they hangup on SIGTERM?)

**Comment by braver** [comment] 2021-04-13 11:46
You might also want to try recent builds of ST4. It’s beta officially but very stable, comes with many fixes, and there is a native Apple Silicon build.

**Comment by sambauers** [comment] 2021-05-08 01:49
It's possible that the problem is actually with the underlying linting tools. I have an M1 and only run my terminal via Rosetta and have never had an issue with SublimeLinter + standardjs + ts-standard + json, all tooling installed via Brew/NVM/NPM. If you use Terminal without Rosetta (directly on Apple Silicon) you may be running into lingering issues with CLI tools on that architecture. Maybe stress test the underlying linters in the Terminal and see if similar issues emerge?

**Comment by sambauers** [comment] 2021-05-09 04:14
@kaste 

> Out of curiosity, how many threads do we actually use here?
> 
> https://github.com/SublimeLinter/SublimeLinter/blob/35a7afe930d9fc8d3e5acc523bfef8a4f21a8256/lint/backend.py#L31-L31
> 
> Is this still a sane value on the M1 procs?

On my M1 Mac `multiprocessing.cpu_count()` returns `8`, which is the number of cores in the M1

**Comment by sambauers** [comment] 2021-05-09 04:33
> You can quickly test overloading the system, just type `s<ctrl+s>s<ctrl+s>s<ctrl+s>s<ctrl+s>s<ctrl+s>s<ctrl+s>` ... (You need to press a char, aka _modify_ the buffer, between saves to trigger a new run.)

I tried this using a typescript file using my ts-standard plugin, which uses `stdin` for background processing. The built-in delay on background processing stopped it calling the linter too often, and repetitive file saving did not cause a spike in CPU either. I just couldn't save the files fast enough manually to overload it.

The `plugin_host` process never even reached 5% of CPU.

I don't doubt that it is an issue for some people (I assume they aren't making things up), but I can't reproduce this behaviour.

**Comment by kaste** [comment] 2021-05-17 17:51
Closing for now as there is no interaction from OP, and no further movement in the forum thread either.  

Thanks @sambauers for the quick tests.  With 8 cores you can't overload *except* if the processes start to hang.  ts-standard probably uses the same technology as eslint so the piping from stdin is maybe not the culprit.  (Of course, eslint *can* really run arbitrary code via the plugins.)

**Closed by kaste** 2021-05-17 17:51 UTC

**Comment by TehShrike** [comment] 2021-05-27 17:39
I solved the issue by updating to ST4, which since it is generally available now, is probably a good enough excuse to leave this ST3+M1 bug alone
