### ISSUE TITLE
WARNING: Waited in queue for <N>s

### ISSUE THREAD

**Issue by Kristinita** [SublimeLinter/SublimeLinter#1364] opened 2018-04-29 09:30 UTC
### 1. Summary

I get in Sublime Text console messages:

```python
SublimeLinter: WARNING: Waited in queue for 7.57s
SublimeLinter: WARNING: Waited in queue for 0.36s
```

They clutter the console and prevent me from reading other messages in the console.

### 2. Environment

+ Sublime Text Build 3143
+ SublimeLinter 4.3.2
+ SublimeLinter-contrib-write-good 2.2.0
+ SublimeLinter-contrib-pydocstyle 3.2.4

### 3. Configuration

my `User/SublimeLinter.sublime-settings` file:

```json
{
    "debug": false,
}
```

### 4. Steps to reproduce

I reproduce the problem in a version of Sublime Text without plugins and user settings.

I open any big Python files ([**`pelicanconf.py`**](https://github.com/Kristinita/KristinitaPelican/blob/master/pelicanconf.py)) and `[**publishconf.py**](https://github.com/Kristinita/KristinitaPelican/blob/master/publishconf.py)` for example → I open Sublime Text console.

### 5. Expected behavior

No `SublimeLinter: WARNING: Waited in queue for <N>s` messages in console.

### 6. Actual behavior

```python
SublimeLinter: WARNING: Waited in queue for 7.57s
SublimeLinter: WARNING: Waited in queue for 0.36s
```

In real, I have 20+ SublimeLinter plugins. I get these warnings in large quantities. This prevents me from working in the console.

Thanks.

**Comment by kaste** [comment] 2018-04-29 18:28
We intentionally warn here starting with 4.3 to get more user feedback and improve SublimeLinter.

There is a setting kill_old_processes or similar named. Could you set this to true?

**Comment by braver** [comment] 2018-04-30 09:46
Also, enable debug and give us the full output. You should not have trouble running just pydocstyle on a relatively tiny files like those.

**Comment by braver** [comment] 2018-05-11 09:06
Closing due to lack of reproduction and response.

**Closed by braver** 2018-05-11 09:06 UTC
Labels: questions & setup

**Comment by Kristinita** [comment] 2018-05-11 09:26
@braver,

### 1. Question

After how many days do you close issues?

### 2. Problem

I think, you close issues a small-time period.

All SublimeLinter users have a lot of another work (*and, for example, [**I have 394 open GitHub issues at the time**](https://github.com/search?utf8=%E2%9C%93&q=author%3AKristinita&type=Issues&ref=searchresults)*). Due to numerous other work, users may not respond in a short period.

### 3. my behavior

I think, that the optimal period is 60 days.

I use [**No Response**](https://probot.github.io/apps/no-response/) [**Probot**](https://probot.github.io/) app for automatically closing issues in my repositories, if user don't respond 60 days. See [**example configuration**](https://github.com/Kristinita/KristinitaPelican/blob/master/.github/no-response.yml).

Thanks.

**Comment by braver** [comment] 2018-05-11 09:43
Usually I give it a week or two at most. Perhaps that’s short, but it’s not like I remove the issue, it’s here for you to re-open. We get a lot of issues where we’re not finding bugs or improving anything, we’re just helping someone debug or configure their setup. We’re just helpdesking here. I get that you may have something better to do and may let it rest for a while, but I want to have it off our list if that happens because it is of no real interest to anyone else. 

Thanks for the link to that bot, I may set that up.
