### ISSUE TITLE
Error loading syntax file 'Packages/SublimeLinter/panel/panel.sublime-syntax': Unable to read Packages/SublimeLinter/panel/panel.sublime-syntax

### ISSUE THREAD

**Issue by darkred** [SublimeLinter/SublimeLinter#1059] opened 2018-03-02 22:55 UTC
_Using ST 3 dev build 3157, SublimeLinter 4.0.2 (without any custom settings, having removed SL 3 and re-installed SL 4), SublimeLinter-eslint 4.0.0, ESlint 4.18.2 in win10x64_

Today, during both upgrades 4.0 -> 4.0.1 and 4.0.1 -> 4.0.2  
I got the following popup error:
```
Error loading syntax file 'Packages/SublimeLinter/panel/panel.sublime-syntax': 
Unable to read Packages/SublimeLinter/panel/panel.sublime-syntax
```  
i.e. 
![2018-03-03_004300](https://user-images.githubusercontent.com/723651/36925700-bfdac840-1e7c-11e8-865c-8e684bbb661a.jpg)

After that, if I restart ST, I have no error popup, no error in console and SL works ok.
Also, I tried enabling ST's debug mode, closed ST and restarted it, I also don't get any error in console.

**Comment by kaste** [comment] 2018-03-02 23:04
AFAIK this is a reported error against PackageControl. SublimeLinter should work okay after a restart. (Of course this is an edge case, usually it should work. 🤞 )

**Comment by darkred** [comment] 2018-03-02 23:38
Yes, it worked ok in both cases after a restart,

What's strange is that I don't have a `panel.sublime-syntax` file in AppData\Roaming\Sublime Text 3\Packages 
(there's no `SublimeLinter` folder insider, even in a fresh ST installation with only SL installed):
![2018-03-03_012356](https://user-images.githubusercontent.com/723651/36926650-94a37e92-1e81-11e8-8601-f1fa76abc970.jpg)
There's only two .cache and .rcache 'panel' files, in AppData\Local\Sublime Text 3\Cache\SublimeLinter
![2018-03-03_012029](https://user-images.githubusercontent.com/723651/36926653-9b59caac-1e81-11e8-9161-8d6e5a693963.jpg)

Maybe this `panel.sublime-syntax` file is missing from SL4 installation?
Or, it's just a leftover reference from SL3? ([search link](https://github.com/SublimeLinter/SublimeLinter/search?q=panel.sublime-syntax&type=Code&utf8=%E2%9C%93))

Is there anything that could be done to solve this?

**Comment by kaste** [comment] 2018-03-03 00:00
SublimeLinter installs 'packaged' in 'Sublime Text 3\\Installed Packages'. 

We just wait if others have an idea.

**Comment by darkred** [comment] 2018-03-03 00:05
Ok, so, in my C:\Users\Kostas\AppData\Roaming\Sublime Text 3\Installed Packages folder, I opened the file SublimeLinter.sublime-package in 7-zip
and there's indeed a 'panel.sublime-syntax' file inside: 
![2018-03-03_020347](https://user-images.githubusercontent.com/723651/36927587-248a7236-1e87-11e8-84c7-d3eb6bdd62bc.jpg)
So, at least the file is not missing.

**Comment by kaste** [comment] 2018-03-03 00:08
@FichteFoll Is that the (or related to the) error you reported on PackageControl? It's been a while, so I don't remember the context here.

**Comment by braver** [comment] 2018-03-03 08:51
It’s a duplicate of this: https://github.com/SublimeLinter/SublimeLinter/issues/964. Has been reported at PC.

**Closed by braver** 2018-03-03 08:51 UTC

**Comment by churiart** [comment] 2018-03-08 09:06
I have the same problem. I tried to remove and reinstall sublimelinter. But again now I got this error when I run sublime text.

What's wrong with `panel.sublime-syntax`? How can I have it? What is it?

**Comment by braver** [comment] 2018-03-08 09:10
It's just some thing that we provide and use but it gets smacked around during upgrades. We're looking into mitigating the issue, but for now you can just ignore it.

**Comment by braver** [comment] 2018-03-16 15:43
I you get the message from the OP all the time you need to do some housekeeping and clean up your ST install (remove caches, re-install SL, etc.).

The other thing sounds like this: https://github.com/SublimeLinter/SublimeLinter/blob/master/docs/troubleshooting.rst#on-macos
