### ISSUE TITLE
max height of tooltip is really small

### ISSUE THREAD

**Issue by slifin** [SublimeLinter/SublimeLinter#1601] opened 2019-05-09 09:30 UTC
I remember historically sublimelinter never did this, I think this was introduced in a major version ages ago

Essentially part of my workflow is to screenshot the linting error for code review purposes
but the max height cuts of the message and gives a very small window for showing lint errors, is it possible to configure the max width and height via settings? or unlocked as default

<img width="1823" alt="Screenshot 2019-05-09 at 10 26 23" src="https://user-images.githubusercontent.com/198857/57442984-009b5300-7245-11e9-84eb-78069149c8f1.png">

**Comment by kaste** [comment] 2019-05-09 11:58
Interesting. The error message is too long to fit on one line, so Sublime wraps it, but it looks like it doesn't recompute or adjust the height of the div. 

@braver, you speak CSS naturally. Isn't that the 'overflow' thing. The text wraps but the box height stays?

I would say it is a Sublime bug. Maybe a regression if you know it worked before. 🤷‍♀ If it is, and we don't do anything stupid with the CSS boxes, then we would have to wrap long lines on our own, manually.

**Comment by kaste** [comment] 2019-05-09 12:00
Related?: https://github.com/SublimeTextIssues/Core/issues/2711
Also?: https://github.com/tomv564/LSP/issues/486#issuecomment-477343716

**Comment by braver** [comment] 2019-05-09 15:40
I can look at it. It’s not real HTML nor real CSS, but there should be something we could do.

**Comment by braver** [comment] 2019-06-03 19:45
Seems really a lot like SublimeTextIssues/Core#2711. We can't set a minimum height or anything else that might help. It seems that as lines wrap, the layout engine that's behind the tooltips doesn't recalculate the required height of the tooltip. Now, I understand these kind of things can get loopy (the size of the box makes the content wrap, so the box needs to be resized, which would change the layout of the content, which then changes the size of the box...), but it seems to take shortcuts here that are unexpected.

There doesn't seem to be anything we can do. I expect that when/if the core issue gets solved our issue will disappear also. I'll close the issue here.

**Comment by kaste** [comment] 2019-06-07 11:08
Unlikely Sublime will fix this. The linked issue doesn't have any comments yet nor labels. The LSP issue doesn't link to any other core issue as well.  

@braver We need better communication between Sublime core and some prominent Sublime plugins. If we just close here nothing will happen. But either we implement wrapping or they commit themself.

**Comment by braver** [comment] 2019-06-07 11:10
🤔 Hard wrapping at 80chars on our end is totally acceptable for me.

**Closed** 2019-06-26 10:17 UTC
