### ISSUE TITLE
Highlights refactoring broke "highlight" import on SublimeLinter-gometalinter

### ISSUE THREAD

**Issue by cixtor** [SublimeLinter/SublimeLinter#916] opened 2018-01-31 19:35 UTC
[This refactoring](https://github.com/SublimeLinter/SublimeLinter/commit/f3a57dc) of the `highlight` module broken the [SublimeLinter-gometalinter](https://github.com/alecthomas/SublimeLinter-contrib-gometalinter) linter. I was going to send a pull-request to the other repository but figured it's better to report the issue here since the code is still under development _(for version 4.0.0)_.

```
reloading plugin SublimeLinter-gometalinter.linter
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/root/Library/Application Support/Sublime Text 3/Packages/SublimeLinter-gometalinter/linter.py", line 16, in <module>
    from SublimeLinter.lint import Linter, highlight, util
ImportError: cannot import name highlight
```

**Comment by braver** [comment] 2018-02-01 08:57
duplicate of #915

**Closed by braver** 2018-02-01 08:57 UTC
