### ISSUE TITLE
Position of highlighted problem doesn't match linter output

### ISSUE THREAD

**Issue by dsl101** [SublimeLinter/SublimeLinter#188] opened 2015-02-06 14:37 UTC
I'm not entirely sure if this is a SublimeLinter problem, or the linter itself (pyflakes), but I'm seeing the wrong occurrence of a string highlighted as being the error. For example, this line of code:

```
print("sub2 force: %s" % force)
```

Looks like this:

![image](https://cloud.githubusercontent.com/assets/900542/6080903/1da479c8-ae0d-11e4-8971-085102eb0e7e.png)

but of course that makes no sense - there can't be a problem _inside_ the string. The error is that the code should read:

```
print("sub2 force: %s" % self.force)
```

and if I chance the word inside the string, the second occurrence _is_ correctly highlighted in that first version. And, the linter output in the status bar says `Error: undefined name 'force', Line 41, Column 34` which is correct, even when the highlight is in the wrong place.

I've used Package Control to install everything, so I'm assuming everything is up to date - not sure how to get the version numbers out of the linter...

**Comment by skj3gg** [comment] 2015-02-08 17:49
Are you using tabs or spaces? While I'm not confident this is the cause, this has been know to cause issues.

**Comment by dsl101** [comment] 2015-02-10 10:08
No - happens exactly the same with zero indentation. However, your comment did lead me to discover this pattern - certainly looks like something to do with word breaks, or valid variable name characters or something. I suspect it's a regex somewhere which needs a tweak when locating the offending string. However, the linter output explicitly gives the column position correctly, so not sure why a regex would be in use here...

![linter](https://cloud.githubusercontent.com/assets/900542/6125325/ba0a3422-b10c-11e4-97c1-d8a3935b03f7.png)

**Comment by braver** [comment] 2017-09-23 11:52
I cannot reproduce this particular example with flake8, or the jshint issue but using eslint for that. flake8 issue 15 does also occur on my machine. @groteworld from the flake8 issue it seems you had a look into this. Did you find out if SL was at fault here or if the specific linters should be fixed?

**Comment by braver** [comment] 2018-01-06 14:32
We have been making [many changes](https://github.com/SublimeLinter/SublimeLinter/blob/master/messages/4.0.0-rc.1.txt) to SublimeLinter, some of which also should have fixed this particular problem.

**Closed by braver** 2018-01-06 14:32 UTC
Labels: bug
