### ISSUE TITLE
[version 4] not working for TSlint

### ISSUE THREAD

**Issue by it6** [SublimeLinter/SublimeLinter#1048] opened 2018-03-02 12:47 UTC
I couldn't get `tslint` to work after the upgrade.

**Comment by braver** [comment] 2018-03-02 12:52
Please enable debug in your settings and post the full output from the console.

**Comment by it6** [comment] 2018-03-02 12:57
Looks like I should source `tslintconfig`. How can I do that.

```
SublimeLinter: SublimeLinter.sublime-package:71: Logging installed; log level INFO
SublimeLinter: #4 SublimeLinter.sublime-package:782: 'tslint' is linting 'worker-shift-info.component.ts'
SublimeLinter: #4 SublimeLinter.sublime-package:1200: tslint: worker-shift-info.component.ts ['/Users/kotamrs/sk/projects/myadp/node_modules/.bin/tslint', '@']
SublimeLinter: #4 SublimeLinter.sublime-package:1203: tslint: cwd: /Users/kotamrs/sk/projects/myadp
SublimeLinter: #4 SublimeLinter.sublime-package:809: tslint output:
    No valid rules have been specified
SublimeLinter: #4 SublimeLinter.sublime-package:850: tslint: No match for line: 'No valid rules have been specified'
```

**Comment by braver** [comment] 2018-03-02 13:03
Ok, can reproduce that. I'll have to look into how tslint gets its config here.

**Comment by kaste** [comment] 2018-03-02 13:11
I made a PR https://github.com/lavrton/SublimeLinter-contrib-tslint/pull/26 if it's that tslint

**Comment by it6** [comment] 2018-03-02 13:28
thanks @kaste, I am able to run `tslint` with your PR.

**Comment by braver** [comment] 2018-03-02 13:41
Jup, works for me. I'm keeping this issue around for reference.

**Comment by braver** [comment] 2018-03-02 17:20
A new version of the tslint plugin is released, so this should be fixed now.

**Closed** 2018-03-02 17:23 UTC
