### ISSUE TITLE
SublimeLinter: ERROR

### ISSUE THREAD

**Issue by maurovieirareis** [SublimeLinter/SublimeLinter#1030] opened 2018-02-28 09:42 UTC
Hi.
I'm not sure if it's a bug from Sublime Linter, but sometimes when I save it to SCSS doc this message appears in console:

SublimeLinter: ERROR:

 Lint task failed.
Traceback (most recent call last):
  File "lint.backend in /Users/mauroreisvieira/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 201, in await_futures
  File "./python3.3/concurrent/futures/_base.py", line 394, in result

**Comment by kaste** [comment] 2018-02-28 11:02
Please open the console, and post the full crash 😄

**Comment by maurovieirareis** [comment] 2018-02-28 11:06
SublimeLinter: ERROR:

 Lint task failed.
Traceback (most recent call last):
  File "lint.backend in /Users/mauroreisvieira/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 201, in await_futures
  File "./python3.3/concurrent/futures/_base.py", line 394, in result
  File "./python3.3/concurrent/futures/_base.py", line 353, in __get_result
  File "./python3.3/concurrent/futures/thread.py", line 54, in run
  File "lint.backend in /Users/mauroreisvieira/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 96, in execute_lint_task
  File "lint.linter in /Users/mauroreisvieira/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 815, in lint
  File "lint.linter in /Users/mauroreisvieira/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 1166, in run
  File "/Users/mauroreisvieira/Library/Application Support/Sublime Text 3/Packages/SublimeLinter-contrib-stylelint/linter.py", line 111, in communicate
    if fileext and not fileext[1:] in self.syntax:
TypeError: 'in <string>' requires string as left operand, not tuple

**Comment by kaste** [comment] 2018-02-28 11:24
Is that on an empty file or new unnamed file?

**Comment by maurovieirareis** [comment] 2018-02-28 11:36
@kaste yes.

**Comment by kaste** [comment] 2018-02-28 11:41
Now the problem is on https://github.com/kungfusheep/SublimeLinter-contrib-stylelint/blame/1d9068ba1bf321cbd26b030bb08edb49adc8ab5a/linter.py#L107

```
	fileext = os.path.splitext(filename)

	# but must be 
	_, fileext = os.path.splitext(filename)
```

But, honestly, they should just delete the complete override of `communicate` here.

**Comment by kaste** [comment] 2018-02-28 11:51
Okay I created a PR https://github.com/kungfusheep/SublimeLinter-contrib-stylelint/pull/55

Closing here.

**Closed by kaste** 2018-02-28 11:51 UTC

**Comment by maurovieirareis** [comment] 2018-02-28 12:11
Thanks @kaste
