### ISSUE TITLE
Panel is not defined

### ISSUE THREAD

**Issue by NekR** [SublimeLinter/SublimeLinter#1140] opened 2018-03-06 21:47 UTC
![image](https://user-images.githubusercontent.com/1189265/37060262-c714dfa2-21a0-11e8-819a-a807c1da6432.png)

```
startup, version: 3126 osx x64 channel: stable
executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: /Users/NekR/Library/Application Support/Sublime Text 3/Packages
state path: /Users/NekR/Library/Application Support/Sublime Text 3/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/NekR/Library/Application Support/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.258904
using gpu buffer for window
loading dictionary Packages/Language - English/en_US.dic
first paint time: 0.367483
using gpu buffer for window
using gpu buffer for window
using gpu buffer for window
using gpu buffer for window
using gpu buffer for window
using gpu buffer for window
startup time: 0.741278
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-pygments
reloading plugin 0_package_control_loader.50-markupsafe
reloading plugin 0_package_control_loader.50-python-markdown
reloading plugin 0_package_control_loader.55-jsonschema
reloading plugin 0_package_control_loader.55-mdpopups
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin SublimeLinter-eslint.linter
reloading plugin SublimeLinter.__init__
reloading plugin SublimeLinter.busy_indicator_view
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.goto_commands
reloading plugin SublimeLinter.highlight_view
reloading plugin SublimeLinter.log_handler
reloading plugin SublimeLinter.message_view
reloading plugin SublimeLinter.panel_view
reloading plugin SublimeLinter.status_bar_view
reloading plugin SublimeLinter.sublime_linter
reloading plugin SublimeLinter.tooltips_view
reloading plugin TrailingSpaces.trailing_spaces
reloading plugin Babel.Babel
reloading plugin JsPrettier.JsPrettier
reloading plugin TypeScript.main
2018-03-07 00:40:53,966: 140735811273664: WARNING: TypeScript plugin initialized.
plugins loaded
lang_service_enabled: True
Path of tsserver.js: /Users/NekR/Library/Application Support/Sublime Text 3/Packages/TypeScript/tsserver/tsserver.js
Path of tsc.js: /Users/NekR/Library/Application Support/Sublime Text 3/Packages/TypeScript/tsserver/tsc.js
Trying to spawn node executable from: /usr/local/bin/node
ref view not found
Package Control: Installing 1 upgrades
ignored packages updated to: ["SublimeLinter", "Vintage"]
unloading plugin SublimeLinter.__init__
unloading plugin SublimeLinter.busy_indicator_view
unloading plugin SublimeLinter.commands
unloading plugin SublimeLinter.goto_commands
unloading plugin SublimeLinter.highlight_view
unloading plugin SublimeLinter.log_handler
unloading plugin SublimeLinter.message_view
unloading plugin SublimeLinter.panel_view
unloading plugin SublimeLinter.status_bar_view
unloading plugin SublimeLinter.sublime_linter
reloading settings Packages/SublimeLinter/SublimeLinter.sublime-settings
unloading plugin SublimeLinter.tooltips_view
generating syntax summary
error: Error loading syntax file "Packages/SublimeLinter/panel/panel.sublime-syntax": Unable to read Packages/SublimeLinter/panel/panel.sublime-syntax
reloading settings Packages/User/Package Control.sublime-settings
Package Control: Upgraded SublimeLinter to 4.0.4
```

**Comment by braver** [comment] 2018-03-06 22:00
Duplicate of #1122

**Closed by braver** 2018-03-06 22:00 UTC
