### ISSUE TITLE
`executable` setting requires `can_lint` override.

### ISSUE THREAD

**Issue by veelo** [SublimeLinter/SublimeLinter#1142] opened 2018-03-06 22:47 UTC
The [`executable`](https://github.com/SublimeLinter/SublimeLinter/blob/master/docs/linter_settings.rst#executable) setting does not work for contributed linters unless they override `can_lint` like
```python
    @classmethod
    def can_lint(cls):
            """Assume the linter can lint."""
            return True
```

**Comment by braver** [comment] 2018-03-07 08:52
Duplicate of #1086

**Closed by braver** 2018-03-07 08:52 UTC
