### ISSUE TITLE
Frequent crashes (Bad file descriptor)

### ISSUE THREAD

**Issue by pedrofoliveira** [SublimeLinter/SublimeLinter#1195] opened 2018-03-13 07:50 UTC
The linter keeps crashing when I build my project (a set of scripts in Ruby). 
I'm using Rubocop underneath.
This is the output I get:
SublimeLinter: #1579 rubocop iplog_dbupdate.rb ERROR:

 Linter crashed.

Traceback (most recent call last):
  File "lint.backend in /Users/poliveir/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 97, in execute_lint_task
  File "lint.linter in /Users/poliveir/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 797, in lint
  File "lint.linter in /Users/poliveir/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 1147, in run
  File "lint.linter in /Users/poliveir/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 1196, in communicate
  File "lint.util in /Users/poliveir/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 225, in communicate
  File "./python3.3/subprocess.py", line 920, in communicate
  File "./python3.3/subprocess.py", line 1556, in _communicate
  File "./python3.3/subprocess.py", line 1664, in _communicate_with_poll
OSError: [Errno 9] Bad file descriptor

**Comment by kaste** [comment] 2018-03-13 21:12
Hi! This is a recent osx, I guess. Can you look if we're spawning too many threads, and if some threads die and lay around for too long. How long takes one lint process normally?

**Comment by kaste** [comment] 2018-03-13 21:14
Aside for python people: Can I catch this OSError and peek at errno == 9? I don't find this error in the module errno.

**Comment by pedrofoliveira** [comment] 2018-03-14 07:42
Hi,
macOs 10.3.3
Not sure if this is what you want but Sublime tends to have between 12 and 18 active threads. I’m getting this from ActivityMonitor.
The Lint process is running in background and I would say it takes less than on second.
The crash is not deterministic and only happens when I build my project.
 
I hope this helps…

**Comment by braver** [comment] 2018-03-14 08:47
10.**13**.3 probably.

**Comment by pedrofoliveira** [comment] 2018-03-14 09:06
Yes, 10.13.3

**Comment by kaste** [comment] 2018-03-14 10:36
Closing in favor of #1061

**Comment by kaste** [comment] 2018-03-14 10:37
Duplicate of #1061

**Closed by kaste** 2018-03-14 10:36 UTC
Labels: duplicate
